name: STATISTIQUES
on:
  workflow_call:
  workflow_dispatch:

jobs:
  STATISTIQUES:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Calcul des statistiques
        run:  |
          git pull origin main
          choco install r.project pandoc --no-progress -y
          Rscript ./SCRIPTS/STATISTIQUES.R
          ### SAUVEGARDE GIT
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "[Bot] Calcul des statistiques"
          git push origin main -f
